# Generated by Django 3.2.10 on 2021-12-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="teams",
        ),
        migrations.AddField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="hr.team"
            ),
        ),
    ]
