# Generated by Django 3.2.10 on 2022-01-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_auto_20211229_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="hiring_date",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hr.team"
            ),
        ),
    ]
